<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <PackageId>Infrastructure.Option</PackageId>
    <Version>10.0.0</Version>    
    <Description>Simple optional type for .NET</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/vilppu/Infrastructure.Option</PackageProjectUrl>
    <RepositoryUrl>https://github.com/vilppu/Infrastructure.Option</RepositoryUrl>
    <IsPackable>true</IsPackable>
    <RootNamespace>Infrastructure</RootNamespace>
    <Authors>Timo Vilppu</Authors>
    <Nullable>enable</Nullable>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Copyright>Copyright (C) 2025 Timo Vilppu</Copyright>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <PackageTags>option, functional, monad, maybe, nullable, csharp, dotnet</PackageTags>
    <Title>Infrastructure.Option – Lightweight Option Type for C# that emphasizes clean, expressive, and readable code</Title>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
</Project>
